name: Run Tests for FIFA Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Set up Google Cloud credentials
      run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > /tmp/credentials.json

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials.json
        PYTHONPATH: ${{ github.workspace }}
      run: python -m unittest discover -s . -p "test_*.py"
